export enum ActionTypes {
    ROLL = 'ROLL',
    FINISH_ROLL = 'FINISH_ROLL',
    BUY_DIE = 'BUY_DIE',
    UPGRADE_DIE = 'UPGRADE_DIE',
    BUY_GLOBAL_UPGRADE = 'APPLY_UPGRADE',
    NEXT_LEVEL = 'NEXT_LEVEL',
    RESET = 'RESET',
}